#!/sbin/busybox sh

cd /sbin

for i in $(./busybox --list)
do
	./busybox ln -s busybox $i
done

cd /

mount -t proc proc /proc
mount -t sysfs sysfs /sys

mkdir -p /dev/block

mknod /dev/block/mmcblk0p20 b 179 20
mknod /dev/block/loop0 b 7 0

mount -t ext4 /dev/block/mmcblk0p20 /system

out() {
	umount -f /system

	chmod 755 /init
	chmod 644 /*.qcom
	chmod 644 /*.rc
	chmod 644 /*.prop
	chmod -R 755 /lib

	exec /init
}

disableKnox() {
	sed 's|ro.securestorage.knox=true|ro.securestorage.knox=false|g' -i /system/build.prop
	sed 's|ro.build.selinux=1|ro.build.selinux=0|g' -i /system/build.prop
	sed 's|ro.config.knox=1|ro.config.knox=0|g' -i /system/build.prop
	sed 's|ro.config.tima=1|ro.config.tima=0|g' -i /system/build.prop
}

mv -f /res/sec442/* /

rm -rf /system/lib/modules/*
ln -s /lib/modules/* /system/lib/modules/

mv -f /res/prima/* /system/etc/firmware/wlan/prima

[ -d /system/app/Synapse.apk ] || mv -f /res/synapse/Synapse.apk /system/app && chmod 644 /system/app/Synapse.apk

disableKnox

out
